version: "3.9"
services:
  apache:
    container_name: php
    restart: always
    build: ./
    networks:
      users:
        ipv4_address: 172.16.239.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./www:/var/www/html"

networks:
  users:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1